### ISSUE TITLE
lametric Spotify app 

### ISSUE THREAD

**Issue by pmchaumien** [WilliamVenner/LaMetric-Spotify#4]
hi William 
I followed all your procedure for create this app but my lametric still displayed "BAD" 
but when I log to my account --> in the app it's OK 
but after some research it's appear that it here where the php stop 
$headers = getallheaders();
	
	if (!isset($headers["Authorization"])) {
		output("BAD"); return;
	}
I put this security to see where is this issue... I don't understand why
Could u help me ?

**Comment by WilliamVenner** [comment]
I believe the Authorization header is set by LaMetric when making a request to the php script.

**Comment by pmchaumien** [comment]
do u have an idea to solve this issue ?
